### ISSUE TITLE
#10 about the definition of signalling exchanges among all nodes

### ISSUE THREAD

**Issue by chenkxyz** [hshokrig/EP3260-MLoNs-2019#10]
Among CA5, we need consider commu. efficiency.
As for the definition of **_signalling exchanges among all nodes_**, I cannot understand how to define it.

My intuition is that master-> slave direction, it has one time signal exchange; slave-> master, it has another signal exchange. 
For instance, in such a 10 slaves- one master topology, in each iteration, it should have 10*2 times signal exchanges.
I dont know if I have correct understanding or not?

Can anyone have good explanation? @hshokrig 
Thank you.

Best
From Hao

**Comment by hshokrig** [comment]
You can count Master to worker like 1 signal (called broadcasting). The workers to master is like 10 signals. Essentially, just count the number of different signals you need to send in that scheme. So like 10+1=11 signals for one round of iterations, not 10+10 = 20.  

This computation is true if you have free broadcasting (from the master node) like the case of wireless channels. But in general, the actual number of signals may depend on particular implementation, so you may observe more than 11. For CA5, it is enough to use 11.
