### ISSUE TITLE
Review assignment for HW-1-2 and CA 1-2

### ISSUE THREAD

**Issue by hshokrig** [hshokrig/EP3260-MLoNs-2019#2]

**Comment by hshokrig** [comment]
- @WenqingYan for SG-1 
- @martisak for SG-2 
- SG-4 reviews SG-9
- SG-6 reviews SG-5
- SG-2 reviews SG-4
- SG-3 review SG-8 
- SG-8 reviews SG-3
- SG-9 review SG-6

Deadline is next Friday, Feb 22.

**Comment by martisak** [comment]
1. group are glad to report that peer-reviews of SG-2's HW1, HW2, CA1 and CA2 are uploaded to the SG-1 branch, moving this issue a little closer to completion. :) We recommend a passing grade for all assignments.

**Comment by hshokrig** [comment]
Thanks for the comment. I suggest all other groups to also put a summary of their review here, like what Martin did.

**Comment by WenqingYan** [comment]
Group 5 already upload the peer-review last Friday. Here, we report the review result of SG-1’s HW1 and CA1. We suggest a passing grade for all assignments. We like your group coding style, clean and well-organised.

**Comment by miladga** [comment]
Group 6 also uploaded the peer-review of HW1, HW2 , CA1 and CA2 for SG5. We give them a "PASS" grade for these assignments.
