### ISSUE TITLE
Review assignment for HW 3 and CA 3

### ISSUE THREAD

**Issue by hshokrig** [hshokrig/EP3260-MLoNs-2019#4]
- SG-3 reviews SG-1
- SG-5 reviews SG-2
- SG-2 reviews SG-3
- SG-1 reviews SG-4
- SG-6 reviews SG-5
- SG-4 reviews SG-6

Deadline is next Wednesday (Lec. 7), Feb 27, 23:59 CET.

**Comment by WenqingYan** [comment]
Here, Group 5 reports the review result of SG-2s HW3 and CA3. We suggest a passing grade for both assignments.

**Comment by kthMLgp3** [comment]
Group 3 reports the review result of SG-1s HW3 and CA3. We suggest a passing grade for both assignments. We particularly liked the clear presentation of HW3.

**Comment by maryamli** [comment]
Group 2 reports the review result of SG-3 HW3 and CA3. We suggest a passing grade for both assignments.

**Comment by martisak** [comment]
Group 1 suggets a a passing grade for SG-5 on CA3 and HW3 (SG-6 will review SG-4 - thanks!).

**Comment by cisprague** [comment]
Group 4 suggests a passing grade for SG-6 on CA3 and HW3.
