### ISSUE TITLE
Send your topic for student workshop on March 20 and 21

### ISSUE THREAD

**Issue by hshokrig** [hshokrig/EP3260-MLoNs-2019#6]
Our student workshop is on March 20 and 21. Each Study Group (SG) is supposed to prepare a 40 minutes oral presentation, followed by 5 minutes Q&A. Each group has also poster presentation during one entire day. You are free to choose the presenter(s) among your SG members. 

There are some potential topics in Slide 1-20. But you are welcome to suggest new topics as well. You should choose some prominent papers (does not have to be new) to cover various aspects of that topic. **Send me ASAP a list of three topics for your group (with your priority ranks).** I will assign the topics to you afterward and your scheduled presentation time. ALL MEMBERS SHOULD PRESENT IN THE WORKSHOP DAYS IF YOU WANT THE COURSE CREDIT. You should inform me if you cannot attend. The valid absence reasons include attending conferences abroad or very urgent family matters.

**Comment by martisak** [comment]
Slide 1-20 in which document?

**Comment by hshokrig** [comment]
Slide x-y is Lecture y slide x.

**Comment by WenqingYan** [comment]
Group 5:
1. Security in MLoNs: Using ML to solve network security problem
2. MLoNs algorithm robustness problem, how to deal with outliers and breakdown points
3. Large-scale ML
Priority: #1 and #2

**Comment by hshokrig** [comment]
Group 5: you can go for "Security in MLoNs: Using ML to solve network security problem"

Please send me the references you gonna use for the oral/poster presentation.

**Comment by martisak** [comment]
Group 1: 
1. MLoNs with partial knowledge
2. Online MLoNs
3. Large-scale ML

**Comment by hshokrig** [comment]
Group 1: you can go for "MLoNs with partial knowledge"

Please send me the references of your oral/poster presentation or let me know if you need any help.

**Comment by maryamli** [comment]
Group 2:
1- Application Areas and Open Research Problems
2- MLoNs with partial knowledge
3- Large-scale ML
Kindly please be informed that topic #1 has the highest priority.

**Comment by hshokrig** [comment]
are you okay with topic 3: Large-scale ML? Item 1 is the subject of an invited talk and also our panel discussion in the workshop, and item 2 has been taken by SG1. Let me know which references you had (have) in mind for topic 1. I am also okay if two groups present the same topic (MLoNs with partial knowledge) if your references are different. 

@martisak are you okay with Online MLoNs? If so, you can take that topic and @maryamli can take MLoNs with partial knowledge.

**Comment by cisprague** [comment]
Group 4:
1. MLoNs with partial knowledge

**Comment by martisak** [comment]
We prefer not to change subject, but if there's no other solution we can switch.

**Comment by hshokrig** [comment]
SG-4 (@cisprague), you can cover Online MLoNs. Please send me your main references.

**Comment by kthMLgp3** [comment]
Hi, here are the preferences of group 3: 
1.      Large-scale ML
2.      Online MLoNs 
3.      Open research problems: applications in communication theory

Our highest priority are topics 1 and 2.

**Comment by hshokrig** [comment]
SG-3 (@kthMLgp3 ), you can go for "Large-scale ML". Please send me your main references.

**Comment by WenqingYan** [comment]
SG-5 Topic-Security in MLoNs: Using ML to solve network security problem
Reference List:
#1. "Network Anomaly Detection: Methods, Systems and Tools": https://ieeexplore.ieee.org/abstract/document/6524462
#2. "A Survey of Outlier Detection Methodologies": https://link.springer.com/article/10.1023/B:AIRE.0000045502.10941.a9?fbclid=IwAR13RNO0bfbY28W9Fo6fTQewbyKdbKu2e0HpEB_jXp07TmaVSL9TLgQ_nyc
#3. "DÏoT : A Self-learning System for Detecting Compromised IoT Devices": https://arxiv.org/abs/1804.07474

**Comment by martisak** [comment]
@hshokrig Are we still assigned "MLoNs with partial knowledge"? A little but unsure how to interpret the "thumbs up"? :)

**Comment by hshokrig** [comment]
yeah @martisak . You can find the assigned topics in the Master branch.

**Comment by cisprague** [comment]
@hshokrig,

The references for group 4 are:
- https://arxiv.org/pdf/1803.10123.pdf
- http://ocobook.cs.princeton.edu/OCObook.pdf

**Comment by martisak** [comment]
SG-1 references.

[1] K. Zhang, Z. Yang, H. Liu, T. Zhang, and T. Başar, “Fully Decentralized Multi-Agent Reinforcement Learning with Networked Agents,” 2018.
[2] H.-T. Wai, Z. Yang, Z. Wang, and M. Hong, “Multi-Agent Reinforcement Learning via Double Averaging Primal-Dual Optimization,” 2018.

**Comment by kthMLgp3** [comment]
SG-3 references

[1] G. Lan, S. Lee, and Y. Zhou, "Communication-Efficient Algorithms for Decentralized and Stochastic Optimization, Mathematical Programming", Dec. 2018.
[2] J Wangni, J Wang, J Liu, T Zhang, "Gradient sparsification for communication-efficient distributed optimization", Advances in Neural Information Processing Systems (NeurIPS), 2018.
