### ISSUE TITLE
Review assignment for CA 4

### ISSUE THREAD

**Issue by hshokrig** [hshokrig/EP3260-MLoNs-2019#8]
SG-2 reviews SG-1
SG-4 reviews SG-2
SG-1 reviews SG-3
SG-5 reviews SG-4
SG-6 reviews SG-5
SG-3 reviews SG-6

Deadline is next Friday, March 08, 23:59 CET.

**Comment by maryamli** [comment]
Group 2 suggest a a passing grade for CA4 of SG-1.

**Comment by WenqingYan** [comment]
Group 5 suggests a passing grade for CA4 from SG-4.

**Comment by cisprague** [comment]
Group 4 suggests a passing grade for CA4 for SG-2.
Great job and nice plots!
